### ISSUE TITLE
Test System Functionality and Identify Bugs

### ISSUE THREAD

**Issue by Powan55** [Powan55/Trivial-Trivia#34]
In order to ensure the robustness and reliability of our application, it's imperative to conduct comprehensive testing of all important system functionalities. This issue encompasses testing to verify that the application performs as intended and to identify any bugs or inconsistencies that may exist.

1. Perform end-to-end testing of all critical system functionalities, including but not limited to:
    - User authentication and login/logout processes.
    - Display of trivia questions and options.
    - Submission and validation of user answers.
    - Scoring calculation and display.
    - Handling of edge cases and error scenarios
    - Data input validation and error handling.
    - UI/UX elements and user interactions.

2. Execute test cases to cover both positive and negative scenarios, ensuring thorough coverage of all possible user interactions and system states.
3. Document any observed bugs, inconsistencies, or unexpected behaviors encountered during testing.
4. Prioritize identified issues based on severity and impact on system functionality.

**Comment by Uttamb7** [comment]
### Test Checklist

- [ ] User authentication and login/logout processes.
- [ ] Display of trivia questions and options.
- [ ] Submission and validation of user answers.
- [ ] Scoring calculation and display.
- [ ] Handling of edge cases and error scenarios
- [ ] Data input validation and error handling.
- [ ] UI/UX elements and user interactions.

### Proposed Changes

1. Please fix the prompt "Please one of the following options:" in Menu
2. Please also fix the exception in thread main when I entered letter it threw an exception.it should have an actual error instead of the exception
3. There was also a bug when I created a account as a user that already existed but the prompt said the account was not created yet I was still able to log into the game.

@Powan55 : These are the changes we should make to improve user experience

**Comment by Powan55** [comment]
@Uttamb7 Please implement those changes.

**Comment by Uttamb7** [comment]
### Proposed Changes Checklist

- [ ] Please fix the prompt "Please one of the following options:" in Menu
- [ ] Please also fix the exception in thread main when I entered letter it threw an exception. It should have an actual error instead of the exception


@Powan55 : All the proposed changes have been implemented please check it out!

**Comment by Powan55** [comment]
Since there have been major changes in the main branch, a new testing issue will be created with a dedicated branch once all the major features have been implemented. This will ensure that our testing aligns with the latest developments. Closing this issue for now.
